### ISSUE TITLE
Distro test on windows fails for no reason

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-dmn-js#101]
__What should we do?__

Fix this: https://github.com/camunda/camunda-dmn-js/actions/runs/8568482468/job/23483403009

__Why should we do it?__

CI failures should be meaningful.

**Comment by nikku** [comment]
Addressed via https://github.com/camunda/camunda-dmn-js/pull/103/commits/83fc4dc4e16cbdd0a24aa9fa3f5a8dcbfa302e24.
