### ISSUE TITLE
Properties Panel Is Detached during Reimport

### ISSUE THREAD

**Issue by nithinssabu** [camunda/camunda-dmn-js#20]
__Describe the Bug__

If the properties panel is dynamically attached, then calling the `importXML` method will cause the properties panel to become invisible. 

__Steps to Reproduce__

1. Load a DMN diagram in the modeler
2. Dynamically attach properties panel 
3. Load another diagram
4. Properties panel becomes invisible

https://codesandbox.io/s/polished-wind-wix5f9?file=/src/index.js

This is causing [this bug](https://github.com/camunda/web-modeler/issues/1986) in Web Modeler. It can be solved by re-attaching the properties panel, but may be it can be solved in the core library as it works without reattaching in the case of BPMN. In fact, we are using the same code for BPMN and DMN and only the modeler instance is different.

__Expected Behavior__

Properties panel is still visible and the properties of the newly loaded diagram is shown in the properties panel.

__Environment__

- OS: Any

**Comment by philippfromme** [comment]
What version of camunda-dmn-js are you using in the Web Modeler?

**Comment by philippfromme** [comment]
v0.5.0 I assume looking at the CodeSandbox.

**Comment by philippfromme** [comment]
I think I found the issue. We recently changed fixed an issue in dmn-js by clearing the editor before a reimport (cf. https://github.com/bpmn-io/dmn-js/issues/697). However, this also unmounts the properties panel. The reason it still works in the Camunda Modeler is this code: https://github.com/camunda/camunda-modeler/blob/v5.2.0/client/src/app/tabs/dmn/DmnEditor.js#L317. I assume you don't have that code in the Web Modeler so that's why the properties panel disappears. The actual bug could be considered detaching the properties panel during reimport, which the callee isn't aware of.

**Comment by philippfromme** [comment]
@barmac Any thoughts on how we could fix this?

**Comment by nithinssabu** [comment]
> v0.5.0 I assume looking at the CodeSandbox.

v0.5.0 it is

**Comment by barmac** [comment]
What I see in the codesandbox:
1. We dynamically attach the properties panel after the initial import.
2. We don't do that after the second import.
I think the first, the second, and later imports should use the same flow, i.e. the properties panel should be dynamically attached after each import.

**Comment by philippfromme** [comment]
So it's expected behavior?

**Comment by barmac** [comment]
I think so. It would a bug if we didn't reattach assuming the container is provided in the config. However, if you decide to manually attach/detach, you need to do that each time you import XML.

**Comment by philippfromme** [comment]
So the fix would be adding the same logic we have in the Camunda Modeler (cf. https://github.com/camunda/camunda-modeler/blob/v5.2.0/client/src/app/tabs/dmn/DmnEditor.js#L317), right?

**Comment by barmac** [comment]
👍

**Comment by philippfromme** [comment]
@nithinssabu Are you okay with replicating the Camunda Modeler behavior? Do you need help?

**Comment by nithinssabu** [comment]
> Are you okay with replicating the Camunda Modeler behavior? Do you need help?

Nope, I can do that.

I was aware that it can be solved by re-attaching the properties panel (as mentioned in the issue description). But it works without re-attaching in the case of BPMN. So we assumed it works the same for DMN.

Wouldn't it be better if it works without re-attaching?

**Comment by barmac** [comment]
Once the properties panel is present in bpmn-js, it can stay as is. In the context of dmn-js however, we display the properties panel only in the DRD view. For decision table and literal expression views it is not available, and that's why we detach it with a new import.

BTW I just noticed that the properties panel is broken in the Web Modeler once you import a DMN without DI, e.g.
[test.dmn.txt](https://github.com/camunda/camunda-dmn-js/files/9380399/test.dmn.txt)

**Comment by nithinssabu** [comment]
> For decision table and literal expression views it is not available, and that's why we detach it with a new import.

I didn't really understand this argument. For me, it makes sense to detach it when switching to decision table & literal expression views but not with new import. May be I don't understand why it has to be this way because I don't know the internals of `dmn-js`. 

I will fix it by re-attaching the properties panel.

**Comment by nithinssabu** [comment]
> once you import a DMN without DI,

@barmac Can you please elaborate on what is DI?

**Comment by barmac** [comment]
DI = diagram interchange

It is the section of the XML which defines diagrams (DRDs), shapes, and connections within them. DMNDI was added in DMN 1.2. We autogenerate DI for DMNs which don't contain DI. You can read more on that in the specification: https://www.omg.org/spec/DMN/

Examples:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" xmlns:dmndi="https://www.omg.org/spec/DMN/20191111/DMNDI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" id="Definitions_0yaknvj" name="DRD" namespace="http://camunda.org/schema/1.0/dmn" xmlns:modeler="http://camunda.org/schema/modeler/1.0" exporter="Camunda Modeler" exporterVersion="5.2.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.0.0">
  <decision id="Decision_0ky6vob" name="Decision 1">
    <decisionTable id="DecisionTable_00114vf">
      <input id="Input_1">
        <inputExpression id="InputExpression_1" typeRef="string">
          <text></text>
        </inputExpression>
      </input>
      <output id="Output_1" typeRef="string" />
    </decisionTable>
  </decision>
  <!-- This is where the DI can be found -->
  <dmndi:DMNDI>
    <dmndi:DMNDiagram>
      <dmndi:DMNShape dmnElementRef="Decision_0ky6vob">
        <dc:Bounds height="80" width="180" x="160" y="100" />
      </dmndi:DMNShape>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
</definitions>
```

It can also look like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" xmlns:dmndi="https://www.omg.org/spec/DMN/20191111/DMNDI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" id="Definitions_0yaknvj" name="DRD" namespace="http://camunda.org/schema/1.0/dmn" xmlns:modeler="http://camunda.org/schema/modeler/1.0" exporter="Camunda Modeler" exporterVersion="5.2.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.0.0">
  <decision id="Decision_0ky6vob" name="Decision 1">
    <decisionTable id="DecisionTable_00114vf">
      <input id="Input_1">
        <inputExpression id="InputExpression_1" typeRef="string">
          <text></text>
        </inputExpression>
      </input>
      <output id="Output_1" typeRef="string" />
    </decisionTable>
  </decision>
</definitions>
```

**Comment by nithinssabu** [comment]
> It is the section of the XML which defines diagrams (DRDs), shapes, and connections within them.

Thanks for the explanation @barmac. I think we can close this issue. I fixed the issue in Web Modeler by re-attaching properties panel after import.
